//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stud
    {
        
        public int Sid { get; set; }
        [Display(Name="First Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string Sfname { get; set; }
        [Display(Name = "Last Name")]
        public string Slname { get; set; }
        [Display(Name = "Age")]
        [Range(15,50,ErrorMessage ="Range between 15 to 50")]
        public Nullable<int> Sage { get; set; }
        [Display(Name = "Gender")]
        public string Sgender { get; set; }
        [Display(Name = "Address")]
        public string Saddress { get; set; }
    }
}
